### ISSUE TITLE
some 2023 papers

### ISSUE THREAD

**Issue by xihuai18** [kaixin96/rl-generalization-paper#5]
### 2023
* [ICLR 2023] [Investigating Multi-Task Pretraining and Generalization in Reinforcement Learning](https://openreview.net/pdf?id=sSt9fROSZRO)
* [ICLR 2023] [Can Agents Run Relay Race with Strangers? Generalization of RL to Out-of-Distribution Trajectories](https://openreview.net/pdf?id=ipflrGaf7ry)
* [ICML2023] [Model-agnostic Measure of Generalization Difficulty](http://proceedings.mlr.press/v202/boopathy23a/boopathy23a.pdf)
* [ICML2023] [On the Power of Pre-training for Generalization in RL: Provable Benefits and Hardness](https://proceedings.mlr.press/v202/ye23a/ye23a.pdf)
* [ICML2023] [The Benefits of Model-Based Generalization in Reinforcement Learning](http://proceedings.mlr.press/v202/young23a/young23a.pdf)

**Comment by kaixin96** [comment]
Thank you @xihuai18 👍
